---
title: "Homework 1 - Report"
author: "Name I, First Name I and Name II, First Name II"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

To obtain the maximum number of points, use whenever possible:

* the pipeline symbol %>%,
* `dplyr` verbs (see below),
* `kable` to print tables,
* `ggplot` to produce the figures.

| verb | description |
| :---  | :---  | :---:  |
| `select()` | select columns |
| `filter()` | filter rows |
| `arrange()` | re-order or arrange rows |
| `mutate()` | create new columns |
| `summarise()` | summarise values |
| `group_by()` | group operations |

```{r setup}
# Some nice options for your reports!

knitr::opts_chunk$set(
  comment = "#>",
  collapse = TRUE,
  # cache = TRUE,
  fig.retina = 0.8, # figures are either vectors or 300 dpi diagrams
  dpi = 300,
  out.width = "70%",
  fig.align = 'center',
  fig.width = 6,
  fig.asp = 0.618,  
  fig.show = "hold"
)

ggplot::theme_set(theme_light())

options(
  digits = 3,
  str = strOptions(strict.width = "cut"),
  width = 69,
  tibble.width = 69,
  cli.unicode = FALSE
)
```

```{r child = 'hw1_ex1.Rmd'}
```

```{r child = 'hw1_ex2.Rmd'}
```

```{r child = 'hw1_ex3.Rmd'}
```

```{r child = 'hw1_ex4.Rmd'}
```